# Generated by Django 5.0.6 on 2024-08-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_caminho"),
    ]

    operations = [
        migrations.CreateModel(
            name="Elemento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
    ]
