# Generated by Django 5.0.6 on 2024-08-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_elemento"),
    ]

    operations = [
        migrations.CreateModel(
            name="Raridade",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tier", models.CharField(max_length=1)),
            ],
        ),
    ]
