# Generated by Django 5.0.6 on 2024-08-19 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_raridade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="raridade",
            name="tier",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=255)),
                ("descricao", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "preco",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name="Preço"
                    ),
                ),
                (
                    "caminho",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="produtos",
                        to="core.caminho",
                    ),
                ),
                (
                    "elemento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="produtos",
                        to="core.elemento",
                    ),
                ),
                (
                    "raridade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="produtos",
                        to="core.raridade",
                    ),
                ),
            ],
        ),
    ]
