# Generated by Django 5.0.6 on 2024-08-22 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_raridade_tier_produto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="raridade",
        ),
        migrations.AddField(
            model_name="produto",
            name="tier",
            field=models.IntegerField(choices=[(4, "4 Estrelas"), (5, "5 Estrelas")], default=4),
        ),
        migrations.CreateModel(
            name="Compra",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("total", models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Carrinho"), (2, "Realizado"), (3, "Pago"), (4, "Entregue")], default=1
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compras",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Carrinho",
        ),
    ]
