# Generated by Django 5.0.6 on 2024-08-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_produto_raridade_produto_tier_compra_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="caminho",
            field=models.IntegerField(
                choices=[
                    (1, "A Destruição"),
                    (2, "A Caça"),
                    (3, "A Erudição"),
                    (4, "A Harmonia"),
                    (5, "A Inexistência"),
                    (6, "A Preservação"),
                    (7, "A Abundância"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="elemento",
            field=models.IntegerField(
                choices=[
                    (1, "Físico"),
                    (2, "Fogo"),
                    (3, "Gelo"),
                    (4, "Raio"),
                    (5, "Vento"),
                    (6, "Quântico"),
                    (7, "Imaginário"),
                ],
                default=1,
            ),
        ),
        migrations.DeleteModel(
            name="Raridade",
        ),
        migrations.DeleteModel(
            name="Caminho",
        ),
        migrations.DeleteModel(
            name="Elemento",
        ),
    ]
