# Generated by Django 5.1 on 2024-08-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_produto_backgroundchar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="descricao",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
