# Generated by Django 5.1 on 2024-08-30 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_produto_descricao"),
        ("uploader", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="caminhoPng",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="uploader.image",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="elementoPng",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="uploader.image",
            ),
        ),
    ]
