# Generated by Django 5.1 on 2024-10-29 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_itenscompra"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="compra",
            name="total",
        ),
    ]
