# Generated by Django 5.1 on 2024-12-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_compra_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="tipo_pagamento",
            field=models.IntegerField(
                choices=[(1, "PIX"), (2, "Cartão de Crédito"), (3, "Cartão de Débito"), (4, "Boleto")], default=1
            ),
        ),
    ]
