from .user import UserSerializer
from .compra import CompraDetailSerializer, CompraSerializer, CriarEditarCompraSerializer, CriarEditarItensCompraSerializer, ItensCompraSerializer
from .produto import ProdutoDetailSerializer, ProdutoListSerializer, ProdutoSerializer